### ISSUE TITLE
Gradle import not work

### ISSUE THREAD

**Issue by yshahak** [tbouron/ShakeDetector#1]
I tried:
     dependencies {
         compile 'com.github.tbouron.shakedetector:library:1.0.0'
    }

But I got:
Unrecognized dependency: 'com.github.tbouron.shakedetector:library:1.0.0' (type: 'aar.asc', extension: 'aar.asc')

**Comment by tbouron** [comment]
Hi!

Humm that's strange, I can see the lib on [maven central](http://search.maven.org/#artifactdetails%7Ccom.github.tbouron.shakedetector%7Clibrary%7C1.0.0%7Caar.asc) and I can add it to any project through Android Studio.

Did you add Maven Central as source repository for your dependencies in your `build.grable` ?

**Comment by yshahak** [comment]
This is how my build.gradle of whole App looks like:

```
buildscript {
  repositories {
      mavenCentral()
  }
dependencies {
       classpath 'com.android.tools.build:gradle:1.2.3'

       // NOTE: Do not place your application dependencies here; they belong
       // in the individual module build.gradle files
   }
}

allprojects {
   repositories {
      mavenCentral()
   }
```

   }

Ans this id the gradle of the module:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

defaultConfig {
    applicationId "com.ysapps.tools.brokenscreen"
    minSdkVersion 11
    targetSdkVersion 22
    versionCode 1
    versionName "1.0"
}
buildTypes {
      release {
          minifyEnabled false
          proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
       }
   }
}
dependencies {
   compile fileTree(dir: 'libs', include: ['*.jar'])
   compile 'com.android.support:appcompat-v7:22.2.1'
   compile 'com.github.tbouron.shakedetector:library:1.0.0'
}
```

**Comment by tbouron** [comment]
Which version of Android Studio are you using? I'm guessing the latest one (1.3-RC4)?

**Comment by yshahak** [comment]
1.3

2015-08-04 12:31 GMT+03:00 Thomas Bouron notifications@github.com:

**Comment by tbouron** [comment]
I'll test it again this week and get back to you as soon as possible

**Comment by moali2402** [comment]
Has this been fixed? As it still not working

**Comment by tbouron** [comment]
I cannot reproduce this use case, it works find on my end.

Did you try to force the aar reference like so:
`compile 'com.github.tbouron.shakedetector:library:1.0.0@aar'`?

**Comment by harryjamesuk** [comment]
I also just had this issue. I tried using the aar reference as @tbouron said and hey presto! Everything's working now!

**Comment by Ailuridaes** [comment]
It's been a bit since the last post, but I wanted to add that I just had this issue as well. My build.gradle files are almost identical to @yshahak (only difference being newer build tools). I added the aar reference and it works like a charm now!

@tbouron, maybe you could add a note to the readme so this solution is easier to find? Thanks for the library by the way, it saved me a lot of time now that I've got it working!

**Comment by tbouron** [comment]
True @Ailuridaes, I completely forgot the issue, apologies.

I just updated the readme :)

**Comment by yshahak** [comment]
Great, well done with the work here!
