### ISSUE TITLE
ShakeDetector.destroy(); in onDestroy() of Fragment don't work and the Shakedetector still working 

### ISSUE THREAD

**Issue by amineghabi** [tbouron/ShakeDetector#2]

**Comment by tbouron** [comment]
Hi @amineghabi.

I'll need more details about this: what do you mean by "the shakedector still working"? Did you call the `ShakeDetector.stop()` method before destroying it?

Also, a stacktrace or any other information would be useful.

**Comment by tbouron** [comment]
No response for almost a year, closing the issue
