### ISSUE TITLE
Detect left and right

### ISSUE THREAD

**Issue by pishguy** [tbouron/ShakeDetector#3]
Hi, who can i know shake detected such as shake phone to right or shake to left?

**Comment by tbouron** [comment]
Hi.

Not sure to follow your question. For the library, a shake is a succession of rapid movements (up, down, left, right) The notion of shake to left or right is meaningless in this context.
Maybe you are talking about a tilt? In that case, Android already provides sensors APIs for it

**Comment by pishguy** [comment]
@tbouron Hi,

you suppose i wrote simple Muzic player appliaction,ok? i want to simulate shake to left for prev muzic and shake to right for next musiz. Thanks

**Comment by tbouron** [comment]
So yeah, what you want is to detect a tilt to the left or right. For that, you should use the [SensorManager](https://developer.android.com/reference/android/hardware/SensorManager.html) ;)
